show events;

SHOW PROCESSLIST;

SELECT EVENT_DEFINITION FROM INFORMATION_SCHEMA.EVENTS WHERE EVENT_NAME='hl7_export_records_choa_0850';

alter table hl7app.adt_msg_queue add column procedure_description varchar(100);


( msg['PV1']['PV1.3']['PV1.3.1'].toString() == '1HALL'
       ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == '2H'
       ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == '3T-ICN'
       ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == '3H-ICN'
       ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == '4HH'
       ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == '4S'
       ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == '5HH'
       ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == '6HALL'
       ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == '6H'
       ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == '2S-PICU'
       ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'SC2S'
       ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'SC3S'
       ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'FHCINPT'

       ( msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'CARC'
        ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'CARDDEV'
        ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'CFC'
        ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'BRNC'
        ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'DENC'
        ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'DMC'
        ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'ENTC'
        ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'GIC'
        ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'GICABD'
        ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'GNC'
        ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'DWSC'
        ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'HEOC'
        ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'BMTC'
        ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'SICC'
        ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'HPC'
        ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'HEMADULT'
        ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'HEMCHILD'
        ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'IDC'
        ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'IDCTVL'
        ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'RENC'
        ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'NEUC'
        ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'NSGC'
        ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'ORTC'
        ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'IPM'
        ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'PLC'
        ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'CLPC'
        ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'PULC'
        ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'RHBC'
        ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'RHC'
        ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'SLEEP CL'
        ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'NEOC'
        ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'ORTC SPORT'
        ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'SGC'
        ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'URO'
        ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'WGT MGT HR'
        ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'DCWTMGSPC'
        ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'DCWGTMGT'

        ( msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'NCALC'
 ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'NCCAR'
 ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'NCDER'
 ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'NCDMC'
 ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'NCEND DIAB'
 ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'NCEND'
 ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'NCENT'
 ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'NCGIC'
 ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'NCGNC'
 ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'NCNEU'
 ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'NCORT'
 ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'NCPULC'
 ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'NCRHBC'
 ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'NCSLEEP CL'
 ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'NCORTCSPOR'
 ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'NCSURG'
 ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'NCWGTMGT'

 ( msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'JOCARC'
       ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'JOCFC'
       ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'BCENDCJOP'
       ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'ENDCJOP'
       ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'JOENDC'
       ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'JODIAB'
       ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'GICJO'
       ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'JOGIC'
       ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'HEOCJOP'
       ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'JOHEOC'
       ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'JOHPC'
       ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'JOPLC'
       ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'RENC JOP'
       ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'JORENC'
       ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'JORHC'


       ( msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'BCENDCPAR'

        ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'ENDCPIT'
        ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'BCENDPITCC'

        ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'BCENDCSAL'
        ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'GICSAL'
        ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'ORTC SAL'

        ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'BCENDCSPF'
        ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'GICSP'
        ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'HEOCSP'
        ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'HPCSPRING'
        ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'ORTC SPRI'
        ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'RHCSPR'
        ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'SJHCARD'
        ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'SJHENDC'
        ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'SJHDIAB'

        ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'WICCARC'
        ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'WICCARDEV'
        ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'WICDIAB'
        ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'WICENDC'
        ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'WICENDMUR'
        ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'WICDIAMUR'
        ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'GICWIC'
        ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'WICHEM'
        ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'WICRENC'
        ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'RENC WIC'
        ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'RENCWICHS'
        ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'WICNSGC'
        ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'ORTC WICH'
        ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'WICPLC'
        ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'WICRHC'
        ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'UROWIC'

        ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'FHC'

        ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'BVUCC'

        ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'NCUCC'

        ||  msg['PV1']['PV1.3']['PV1.3.1'].toString() == 'ECUCC'
